version: '2'

services:
  backend:
    image: 'cn_maturity_matrix_backend'
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    image: 'docker.io/library/postgres:14'
    container_name: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  frontend:
    image: 'cn_maturity_matrix_frontend'
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8081:8081"
