export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/cn_maturity_matrix
export SPRING_DATASOURCE_USERNAME=compose-postgres
export SPRING_DATASOURCE_PASSWORD=compose-postgres
export SPRING_JPA_HIBERNATE_DDL_AUTO=update
